### ISSUE TITLE
[Request] Feature: Call Modloader from Menu

### ISSUE THREAD

**Issue by Shadpw2** [RyanWalpoleEnterprises/The-Potato-Farm-SDVM#15]
Please make a button that lets me open the mod loader from the main menu.

Bean.

:P

**Comment by RWELabs** [comment]
Create branch for the actual mod so it can be worked on independently of the main application and it's development cycle.

**Link to branch:**
> [https://github.com/RWELabs/Stardew-Valley-Mod-Manager/tree/SDVMM-Mod](https://github.com/RWELabs/Stardew-Valley-Mod-Manager/tree/SDVMM-Mod)

**Comment by RyanWalpole** [comment]
Was incorrectly added to the "Fixed In Release" category. Have resolved, moved back to To-Do.

**Comment by RyanWalpole** [comment]
**Feature Request Update**

Howdy @Shadpw2, 

Thanks for your feature request/idea. It's been over two years, so we doubt you're hankering for this feature at this point, but I want to explain a little why we're going to be shelving this idea.
Firstly, implementing a way to access the Stardew Valley Mod Manager from within game would require us to develop an actual mod for the game, which while possible - goes a little further than the scope of what we're trying to achieve for the project.
Secondly, and probably most importantly, Stardew Valley and SMAPI are not made with the intention for users to hot-swap mods during their playtime. By adding an in-game way to jump to the mod manager, we are theoretically encouraging users to make mod changes - which may cause an instability in more than just the mod manager, but the game and modding API itself.

While the idea is solid and at first I thought it quite appealing, it presents a few issues and encourages some bad habits. At the moment, if a user launches the modded Stardew Valley experience using the "Launch Game" button, the mod manager stays open in the background, which I think is a comfortable middle ground.

Thanks for your suggestion, nonetheless!
