### ISSUE TITLE
[Issue] Access denied when trying to install modpack

### ISSUE THREAD

**Issue by RyanWalpole** [RyanWalpoleEnterprises/The-Potato-Farm-SDVM#88]
### The Issue or Bug

When attempting to install a modpack, the application throws an error when trying to copy over a mod to the inactive-mods folder.

### Version

220703 (Observed)
all versions from 220703 - 240401

### Operating System

Windows 10

### Steps to reproduce the behavior

1. Attempt to install modpack
2. Observe error

### Screenshots

![image](https://user-images.githubusercontent.com/69621127/179148858-125a014a-bbd9-473c-85f3-5453c40d0fbe.png)

### Additional Context

- User attempted to install the modpack with administrator privileges and had the same issue.
- User noted attempting to make the folders not read only.

**Comment by RyanWalpole** [comment]
Have made SDV Mod Manager launch with high privileges to try combat this issue as it's still looming.

**Comment by RWELabs** [comment]
Issue is persistent in v240401 - reopening issue and merging #124

**Comment by RyanWalpole** [comment]
Issue is present in version 240501 when it comes to mod uninstallation - but was fixed when it comes to enabling, disabling and installing mods and modpacks. Child issue #132 has been opened, and this will be re-opened for now, also.
